from datetime import UTC, datetime
from unittest.mock import AsyncMock, MagicMock

import pytest
from httpx import ASGITransport, AsyncClient

from knowledgenexus.indexing.domain.enums.source_type import SourceType
from knowledgenexus.indexing.domain.models.ingest_job import IngestJob, IngestJobStatus
from knowledgenexus.shared.di.container import AppContainer


@pytest.fixture
async def api_client(monkeypatch):
    ingest_job_repo = AsyncMock()
    ingest_job_repo.get_by_id.return_value = None

    engine = MagicMock()
    conn = AsyncMock()
    conn.exec_driver_sql = AsyncMock()
    engine.connect.return_value.__aenter__.return_value = conn
    engine.connect.return_value.__aexit__.return_value = None

    vector_store = AsyncMock()
    vector_store.health_check.return_value = True

    settings = MagicMock(
        storage_mode=MagicMock(value="hybrid"),
        qdrant_url="http://localhost:6333",
    )

    container = AppContainer(
        settings=settings,
        engine=engine,
        session_factory=MagicMock(),
        chunk_repo=MagicMock(),
        document_repo=MagicMock(),
        ingest_job_repo=ingest_job_repo,
        vector_store=vector_store,
        chunk_storage=MagicMock(),
    )
    # Let the ingest preflight pass; configuration refusal has its own tests.
    container.confluence_ingest_config_problems = lambda: []

    async def fake_init_container(settings):
        return container

    async def fake_shutdown_container():
        return None

    import importlib
    import knowledgenexus.shared.di.container as container_module

    monkeypatch.setattr(container_module, "init_container", fake_init_container)
    monkeypatch.setattr(container_module, "shutdown_container", fake_shutdown_container)

    ingest_module = importlib.import_module("knowledgenexus.presentation.api.v1.ingest_job")
    monkeypatch.setattr(ingest_module, "get_container", lambda: container)

    app_module = importlib.import_module("knowledgenexus.presentation.api.app")
    app = app_module.app

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test") as client:
        yield client, ingest_job_repo


def _make_job(
    *,
    job_id: str = "job-001",
    status: IngestJobStatus = IngestJobStatus.PENDING,
) -> IngestJob:
    return IngestJob(
        id=job_id,
        source_type=SourceType.CONFLUENCE,
        status=status,
        started_at=datetime(2026, 7, 15, 10, 0, 0, tzinfo=UTC),
        completed_at=None,
        error=None,
        stats={"chunks": 0},
    )


@pytest.mark.asyncio
async def test_create_ingest_job_success(api_client):
    client, ingest_job_repo = api_client

    response = await client.post(
        "/api/v1/ingest-jobs",
        json={
            "source_type": "CONFLUENCE",
            "stats": {"chunks": 0},
        },
    )

    assert response.status_code == 201
    payload = response.json()
    assert payload["source_type"] == "CONFLUENCE"
    assert payload["status"] == "pending"
    assert payload["stats"] == {"chunks": 0}
    assert payload["id"]  # UUID generated by server
    assert payload["started_at"]  # timestamp generated by server
    ingest_job_repo.create.assert_awaited_once()


@pytest.mark.asyncio
async def test_get_ingest_job_success(api_client):
    client, ingest_job_repo = api_client
    job = _make_job(status=IngestJobStatus.RUNNING)
    ingest_job_repo.get_by_id.return_value = job

    response = await client.get("/api/v1/ingest-jobs/job-001")

    assert response.status_code == 200
    payload = response.json()
    assert payload["id"] == "job-001"
    assert payload["status"] == "running"
    assert payload["source_type"] == "CONFLUENCE"


@pytest.mark.asyncio
async def test_get_ingest_job_not_found(api_client):
    client, ingest_job_repo = api_client
    ingest_job_repo.get_by_id.return_value = None

    response = await client.get("/api/v1/ingest-jobs/nonexistent")

    assert response.status_code == 404
    assert "not found" in response.json()["detail"]


@pytest.mark.asyncio
async def test_update_ingest_job_success(api_client):
    client, ingest_job_repo = api_client
    existing = _make_job(status=IngestJobStatus.PENDING)
    ingest_job_repo.get_by_id.return_value = existing

    response = await client.patch(
        "/api/v1/ingest-jobs/job-001",
        json={
            "status": "completed",
            "completed_at": "2026-07-15T11:00:00Z",
            "stats": {"chunks": 50, "documents": 5},
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["status"] == "completed"
    assert payload["stats"] == {"chunks": 50, "documents": 5}
    ingest_job_repo.update.assert_awaited_once()
    updated_job = ingest_job_repo.update.await_args.args[0]
    assert updated_job.status == IngestJobStatus.COMPLETED


@pytest.mark.asyncio
async def test_update_ingest_job_failed_status(api_client):
    client, ingest_job_repo = api_client
    existing = _make_job(status=IngestJobStatus.RUNNING)
    ingest_job_repo.get_by_id.return_value = existing

    response = await client.patch(
        "/api/v1/ingest-jobs/job-001",
        json={
            "status": "failed",
            "completed_at": "2026-07-15T10:05:00Z",
            "error": "Connection timeout",
        },
    )

    assert response.status_code == 200
    payload = response.json()
    assert payload["status"] == "failed"
    assert payload["error"] == "Connection timeout"


@pytest.mark.asyncio
async def test_update_ingest_job_keeps_stats_when_omitted(api_client):
    """Omitting `stats` must leave the stored progress alone, not erase it.

    `stats` carries the subtree ingest phase/counters, so an unconditional
    assignment dropped live progress on any partial PATCH.
    """
    client, ingest_job_repo = api_client
    existing = _make_job(status=IngestJobStatus.RUNNING)
    existing.stats = {"phase": "capture_pages", "captured_pages": 12}
    ingest_job_repo.get_by_id.return_value = existing

    response = await client.patch(
        "/api/v1/ingest-jobs/job-001",
        json={"status": "failed", "error": "Connection timeout"},
    )

    assert response.status_code == 200
    assert response.json()["stats"] == {"phase": "capture_pages", "captured_pages": 12}


@pytest.mark.asyncio
async def test_update_ingest_job_not_found(api_client):
    client, ingest_job_repo = api_client
    ingest_job_repo.get_by_id.return_value = None

    response = await client.patch(
        "/api/v1/ingest-jobs/nonexistent",
        json={"status": "completed"},
    )

    assert response.status_code == 404
    ingest_job_repo.update.assert_not_called()


@pytest.mark.asyncio
async def test_confluence_subtree_duplicate_returns_existing_active_job(api_client):
    client, ingest_job_repo = api_client
    existing = _make_job(job_id="existing", status=IngestJobStatus.RUNNING)
    existing.active_key = "a" * 64
    existing.stats = {"phase": "capture_pages", "captured_pages": 12}
    ingest_job_repo.create_or_get_active.return_value = (existing, False)

    response = await client.post(
        "/api/v1/ingest-jobs/confluence-subtrees",
        json={"url": "https://confluence.example.test/spaces/ENG/pages/123"},
    )

    assert response.status_code == 202
    assert response.json()["id"] == "existing"
    ingest_job_repo.create_or_get_active.assert_awaited_once()
    submitted = ingest_job_repo.create_or_get_active.await_args.args[0]
    assert submitted.active_key is not None
    assert "url" not in submitted.stats


@pytest.mark.asyncio
async def test_confluence_subtree_rejects_ip_literal_before_job_creation(api_client):
    client, ingest_job_repo = api_client

    response = await client.post(
        "/api/v1/ingest-jobs/confluence-subtrees",
        json={"url": "https://127.0.0.1/spaces/ENG/pages/123"},
    )

    assert response.status_code == 400
    ingest_job_repo.create_or_get_active.assert_not_called()


@pytest.mark.asyncio
async def test_sync_apply_queues_a_sync_task_under_the_subtree_submission_key(api_client):
    client, ingest_job_repo = api_client
    ingest_job_repo.create_or_get_active.side_effect = lambda job: (job, True)
    import importlib
    ingest_module = importlib.import_module("knowledgenexus.presentation.api.v1.ingest_job")
    container = ingest_module.get_container()
    queue = container.get_confluence_ingest_queue()

    url = "https://confluence.example.test/spaces/ENG/pages/123"
    response = await client.post("/api/v1/ingest-jobs/confluence-subtrees/sync-apply", json={"url": url})

    assert response.status_code == 202
    assert response.json()["stats"]["kind"] == "sync_apply"
    task = queue.get_nowait()
    assert task.kind == "sync_apply"
    assert task.url == url
    # A sync and a plain ingest of the same root must contend for one key, so
    # they can never mutate the same index concurrently.
    submitted = ingest_job_repo.create_or_get_active.call_args.args[0]
    assert submitted.active_key == ingest_module._submission_key(url)


@pytest.mark.asyncio
async def test_sync_preview_queues_a_read_only_task(api_client):
    client, ingest_job_repo = api_client
    ingest_job_repo.create_or_get_active.side_effect = lambda job: (job, True)
    import importlib
    ingest_module = importlib.import_module("knowledgenexus.presentation.api.v1.ingest_job")
    queue = ingest_module.get_container().get_confluence_ingest_queue()

    response = await client.post(
        "/api/v1/ingest-jobs/confluence-subtrees/sync-preview",
        json={"url": "https://confluence.example.test/spaces/ENG/pages/123"},
    )

    assert response.status_code == 202
    assert queue.get_nowait().kind == "sync_preview"


@pytest.mark.asyncio
async def test_resume_keeps_a_sync_job_a_sync_job(api_client, monkeypatch):
    client, ingest_job_repo = api_client
    job = _make_job(job_id="job-sync", status=IngestJobStatus.FAILED)
    job.stats = {"phase": "failed", "resumable": True, "kind": "sync_apply"}
    ingest_job_repo.get_by_id.return_value = job
    import importlib
    ingest_module = importlib.import_module("knowledgenexus.presentation.api.v1.ingest_job")
    container = ingest_module.get_container()
    canonical = "https://confluence.example.test/spaces/ENG/pages/123"
    ingestor = MagicMock()
    ingestor.resume_url.return_value = canonical
    container.get_confluence_subtree_ingestor = lambda: ingestor

    async def fake_resolve(url, _container):
        return ("https://confluence.example.test", "ENG", "123")

    monkeypatch.setattr(ingest_module, "_resolve_canonical_url", fake_resolve)
    queue = container.get_confluence_ingest_queue()

    response = await client.post("/api/v1/ingest-jobs/job-sync/resume")

    assert response.status_code == 202
    assert queue.get_nowait().kind == "sync_apply"
