from __future__ import annotations
from typing import Protocol
from knowledgenexus.foundation.domain.models.confluence_crawl_batch import BatchCheckpoint, BatchFailureCategory, BatchLease, BatchMetrics

class BatchLeaseConflict(Exception):
    pass

class ConfluenceCrawlBatchPort(Protocol):
    def create(self, checkpoint: BatchCheckpoint) -> BatchCheckpoint: ...
    def claim(self, batch_id: str, *, token: str, now: float, lease_seconds: float) -> BatchLease: ...
    def renew(self, lease: BatchLease, *, now: float, lease_seconds: float) -> BatchLease: ...
    def commit(self, lease: BatchLease, *, batch_digest: str, metrics: BatchMetrics, now: float) -> BatchCheckpoint: ...
    def fail(self, lease: BatchLease, *, category: BatchFailureCategory, now: float) -> BatchCheckpoint: ...
    def requeue(self, lease: BatchLease, *, category: BatchFailureCategory, now: float) -> BatchCheckpoint: ...
    def get(self, batch_id: str) -> BatchCheckpoint: ...

    def list_next_pending(self, limit: int, after_ordinal: int | None = None) -> tuple[BatchCheckpoint, ...]: ...
